from __future__ import annotations

import json
import logging
from pathlib import Path
import shutil
import threading
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.store import SQLiteStore


class IngestWorker:
    def __init__(
        self,
        store: SQLiteStore,
        logger: logging.Logger,
        data_dir: Path,
        poll_interval_seconds: float = 0.05,
        processing_delay_seconds: float = 0.1,
    ) -> None:
        self._store = store
        self._logger = logger
        self._data_dir = Path(data_dir)
        self._poll_interval_seconds = poll_interval_seconds
        self._processing_delay_seconds = processing_delay_seconds
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None

    def start(self) -> None:
        if self._thread is not None and self._thread.is_alive():
            return

        self._stop_event.clear()
        self._thread = threading.Thread(target=self._run, name='songcraft-ingest-worker', daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._stop_event.set()
        if self._thread is not None:
            self._thread.join(timeout=2)

    def _write_source_artifacts(
        self,
        job: dict[str, str],
        source: dict[str, str],
        *,
        job_status: str,
        source_status: str,
    ) -> None:
        persisted_job = self._store.get_job(project_id=job['project_id'], job_id=job['id'])
        if persisted_job is None:
            raise RuntimeError('Missing job while writing ingest artifacts')

        source_dir = self._data_dir / 'projects' / job['project_id'] / job['source_id']
        source_dir.mkdir(parents=True, exist_ok=True)

        persisted_media_path, persisted_media_bytes = self._persist_source_media(source_dir=source_dir, source=source)

        manifest = {
            'project_id': job['project_id'],
            'source_id': job['source_id'],
            'job_id': job['id'],
            'job_type': persisted_job['job_type'],
            'job_status': job_status,
            'source_kind': source['kind'],
            'source_status': source_status,
            'source_value': source['value'],
            'persisted_media_path': persisted_media_path,
            'persisted_media_bytes': persisted_media_bytes,
            'job_created_at': persisted_job['created_at'],
            'job_updated_at': persisted_job['updated_at'],
            'source_created_at': source['created_at'],
            'source_updated_at': source['updated_at'],
        }
        manifest_path = source_dir / 'manifest.json'
        raw_source_path = source_dir / 'raw_source.txt'
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding='utf-8')
        raw_source_path.write_text(source['value'], encoding='utf-8')
        self._logger.info('Wrote ingest artifacts for job %s to %s', job['id'], source_dir)

    def _persist_source_media(self, *, source_dir: Path, source: dict[str, str]) -> tuple[str, int | None]:
        if source['kind'] == 'youtube':
            reference_path = source_dir / 'source_reference.url'
            reference_path.write_text(source['value'], encoding='utf-8')
            return ('source_reference.url', None)

        if source['kind'] in {'local_file', 'upload'}:
            original_path = Path(source['value'])
            if not original_path.exists() or not original_path.is_file():
                raise RuntimeError(f"Source media file does not exist: {original_path}")

            media_dir = source_dir / 'source_media'
            media_dir.mkdir(parents=True, exist_ok=True)
            destination_path = media_dir / original_path.name
            shutil.copy2(original_path, destination_path)
            return (str(destination_path.relative_to(source_dir)), destination_path.stat().st_size)

        raise RuntimeError(f"Unsupported source kind for ingest persistence: {source['kind']}")

    def _write_transcription_artifacts(self, job: dict[str, str], source: dict[str, str]) -> None:
        source_dir = self._data_dir / 'projects' / job['project_id'] / job['source_id']
        source_dir.mkdir(parents=True, exist_ok=True)
        transcription_dir = source_dir / 'transcription'
        transcription_dir.mkdir(parents=True, exist_ok=True)

        ingest_manifest = self._store.get_source_artifact_manifest(
            project_id=job['project_id'],
            source_id=job['source_id'],
            data_dir=self._data_dir,
        )
        if ingest_manifest is None:
            raise RuntimeError('Missing ingest manifest while writing transcription artifacts')

        transcript_text = (
            f"Transcript scaffold for source {source['id']} from {source['kind']} input.\n"
            f"Original source: {source['value']}\n"
            f"Persisted media: {ingest_manifest['persisted_media_path']}\n"
            f"This placeholder transcript was generated by the transcribe worker.\n"
        )
        transcript_payload = {
            'project_id': job['project_id'],
            'source_id': job['source_id'],
            'job_id': job['id'],
            'job_type': job['job_type'],
            'source_kind': source['kind'],
            'source_value': source['value'],
            'persisted_media_path': ingest_manifest['persisted_media_path'],
            'segments': [
                {
                    'start_seconds': 0.0,
                    'end_seconds': 5.0,
                    'text': f"Placeholder transcript excerpt for {source['value']}",
                }
            ],
        }

        (transcription_dir / 'transcript.txt').write_text(transcript_text, encoding='utf-8')
        (transcription_dir / 'transcript.json').write_text(
            json.dumps(transcript_payload, indent=2, sort_keys=True),
            encoding='utf-8',
        )
        self._logger.info('Wrote transcription artifacts for job %s to %s', job['id'], transcription_dir)

    def _process_transcribe_job(self, job: dict[str, str]) -> None:
        self._logger.info('Processing transcribe job %s for source %s', job['id'], job['source_id'])
        if self._stop_event.wait(self._processing_delay_seconds):
            return

        source = self._store.get_source(project_id=job['project_id'], source_id=job['source_id'])
        if source is None:
            raise RuntimeError('Missing source while processing transcribe job')
        if source['status'] != 'completed':
            raise RuntimeError('Transcribe job requires a completed source')

        self._write_transcription_artifacts(job, source)
        completed_job = self._store.update_job_status(
            project_id=job['project_id'],
            job_id=job['id'],
            status='completed',
        )
        if completed_job is not None:
            self._logger.info('Completed transcribe job %s', completed_job['id'])

    def _process_ingest_job(self, job: dict[str, str]) -> None:
        self._logger.info('Processing ingest job %s for source %s', job['id'], job['source_id'])
        if self._stop_event.wait(self._processing_delay_seconds):
            return

        source = self._store.get_source(project_id=job['project_id'], source_id=job['source_id'])
        if source is None:
            raise RuntimeError('Missing source while processing ingest job')
        if 'fail' in source['value']:
            raise RuntimeError('Simulated ingest failure for recovery testing')

        self._write_source_artifacts(
            job,
            source,
            job_status='completed',
            source_status='completed',
        )
        completed_job = self._store.update_job_status(
            project_id=job['project_id'],
            job_id=job['id'],
            status='completed',
        )
        if completed_job is not None:
            self._logger.info('Completed ingest job %s', completed_job['id'])

        transcribe_job = self._store.maybe_queue_transcribe_job(
            project_id=job['project_id'],
            source_id=job['source_id'],
            data_dir=self._data_dir,
        )
        if transcribe_job is None:
            return

        self._logger.info('Queued transcribe job %s after ingest job %s', transcribe_job['id'], job['id'])
        running_transcribe_job = self._store.update_job_status(
            project_id=transcribe_job['project_id'],
            job_id=transcribe_job['id'],
            status='running',
        )
        if running_transcribe_job is None:
            raise RuntimeError('Failed to transition queued transcribe job to running')
        self._process_transcribe_job(running_transcribe_job)

    def _run(self) -> None:
        while not self._stop_event.is_set():
            job = self._store.claim_next_queued_job('ingest')
            if job is None:
                self._stop_event.wait(self._poll_interval_seconds)
                continue

            try:
                self._process_ingest_job(job)
            except Exception:
                self._logger.exception('Ingest job %s failed', job['id'])
                current_job = self._store.get_job(project_id=job['project_id'], job_id=job['id'])
                if current_job is not None and current_job['status'] == 'running':
                    self._store.update_job_status(
                        project_id=job['project_id'],
                        job_id=job['id'],
                        status='failed',
                    )
